package Tutorials;

//Guess a random number generated by computer.
import java.util.Scanner;
import java.util.Random;

public class T01Q12 {
    public static void main(String[] args) {
        Random rnd = new Random();
        int x = rnd.nextInt(101);
        Scanner scn = new Scanner(System.in);
        System.out.println("Guess the number between 0-100 : ");
        int ans = scn.nextInt();
        
        if (x == ans){
            System.out.println("Correct! The answer is " + x);
        }
        else{
            System.out.println("False! The answer is " + x);
        }
    }
}//ぶるぶ:3
