package Tutorials;

//Print the minimum number from 10 random numbers generated by computer.

import java.util.Random;

public class T01Q06 {
    public static void main(String[] args) {
        Random rnd = new Random();
        int[] rndnum = new int[10];
        int min = Integer.MAX_VALUE;       //Initial value for min
        
        for (int i = 0; i < 10; i++){
            rndnum[i] = rnd.nextInt(100);  //The highest value the number can get is until 100
            System.out.println("Number " + (i+1) + ": " + rndnum[i]);  //Displays all the values for the 10 numbers
            if (rndnum[i] < min){
                min = rndnum[i];
            }
        }
        System.out.println("The minimum number is : " + min);
    }
}//ぶるぶ:3
